### ISSUE TITLE
Phone rotation

### ISSUE THREAD

**Issue by OmkoBass** [JoeyEamigh/react-native-text-recognition#2]
I checked the source code out and if you have the time you should implemented the camera rotation value. Since some react native camera libraries don't give you the rotation.

There's an example here: https://developers.google.com/ml-kit/vision/text-recognition/android

I'd do a pull request but i'm not that good java. Thanks.

**Comment by JoeyEamigh** [comment]
That is just assuming that the photo's orientation has already been fixed. Horizontal images and such work for me as long as `fixOrientation` is set. If you have different experiences let me know.
